name: Build Electron App for Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install 

    - name: Build Electron app for Linux
      run: npx electron-builder --linux  # Build for Linux (AppImage, .deb, .tar.xz, etc.)

  
    
