name: Build and Publish Windows Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your repository

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up the Node.js environment
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install dependencies
      run: npm install 

    - name: Build Windows app
      run: npx electron-builder -w  # Build for Windows
      env:
        CI: true  # Ensure no interactive prompts

    
